package com.bancosantander.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class fechasProceso implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Fecha Corte de Pago")
	private java.util.Date fechaCorte;
	@org.kie.api.definition.type.Label(value = "Fecha límite Pago")
	private java.util.Date fechaLimitePago;
	@org.kie.api.definition.type.Label(value = "Fecha de Pago")
	private java.util.Date fechaPago;

	public fechasProceso() {
	}

	public java.util.Date getFechaCorte() {
		return this.fechaCorte;
	}

	public void setFechaCorte(java.util.Date fechaCorte) {
		this.fechaCorte = fechaCorte;
	}

	public java.util.Date getFechaLimitePago() {
		return this.fechaLimitePago;
	}

	public void setFechaLimitePago(java.util.Date fechaLimitePago) {
		this.fechaLimitePago = fechaLimitePago;
	}

	public java.util.Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(java.util.Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	public fechasProceso(java.util.Date fechaCorte,
			java.util.Date fechaLimitePago, java.util.Date fechaPago) {
		this.fechaCorte = fechaCorte;
		this.fechaLimitePago = fechaLimitePago;
		this.fechaPago = fechaPago;
	}

}