package com.bancosantander.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class inputPeriodo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Pago mínimo TC")
	private java.lang.Integer pagoMinimoTc;
	@org.kie.api.definition.type.Label("Compras acumuladas")
	private java.lang.Integer montoAcumulado;
	@org.kie.api.definition.type.Label("Pago TC")
	private java.lang.Integer pagoTc;
	@org.kie.api.definition.type.Label("Canales Digitales")
	private java.lang.String canalesDigitales;

	public java.lang.Integer getPagoMinimoTc() {
		return this.pagoMinimoTc;
	}

	public void setPagoMinimoTc(java.lang.Integer pagoMinimoTc) {
		this.pagoMinimoTc = pagoMinimoTc;
	}

	public java.lang.Integer getMontoAcumulado() {
		return this.montoAcumulado;
	}

	public void setMontoAcumulado(java.lang.Integer montoAcumulado) {
		this.montoAcumulado = montoAcumulado;
	}

	public java.lang.Integer getPagoTc() {
		return this.pagoTc;
	}

	public void setPagoTc(java.lang.Integer pagoTc) {
		this.pagoTc = pagoTc;
	}

	public java.lang.String getCanalesDigitales() {
		return this.canalesDigitales;
	}

	public void setCanalesDigitales(java.lang.String canalesDigitales) {
		this.canalesDigitales = canalesDigitales;
	}

	public inputPeriodo() {
	}

	public inputPeriodo(java.lang.Integer pagoMinimoTc,
			java.lang.Integer montoAcumulado, java.lang.Integer pagoTc,
			java.lang.String canalesDigitales) {
		this.pagoMinimoTc = pagoMinimoTc;
		this.montoAcumulado = montoAcumulado;
		this.pagoTc = pagoTc;
		this.canalesDigitales = canalesDigitales;
	}
}