package com.bancosantander.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class variableSostenida implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "TC Domiciliada")
	private java.lang.String tcDomiciliada;
	@org.kie.api.definition.type.Label(value = "Pago Recurrente")
	private java.lang.String pagoRecurrente;
	@org.kie.api.definition.type.Label(value = "Nómina")
	private java.lang.String nomina;
	@org.kie.api.definition.type.Label(value = "Asistent. Contratada")
	private java.lang.String asistentContratada;

//Contructor de la clase
	public variableSostenida(java.lang.String tcDomiciliada,
			java.lang.String pagoRecurrente, java.lang.String nomina,
			java.lang.String asistentContratada) {
		this.tcDomiciliada = tcDomiciliada;
		this.pagoRecurrente = pagoRecurrente;
		this.nomina = nomina;
		this.asistentContratada = asistentContratada;
	}

	public variableSostenida() {
	}

	public java.lang.String getTcDomiciliada() {
		return this.tcDomiciliada;
	}

	public void setTcDomiciliada(java.lang.String tcDomiciliada) {
		this.tcDomiciliada = tcDomiciliada;
	}

	public java.lang.String getPagoRecurrente() {
		return this.pagoRecurrente;
	}

	public void setPagoRecurrente(java.lang.String pagoRecurrente) {
		this.pagoRecurrente = pagoRecurrente;
	}

	public java.lang.String getNomina() {
		return this.nomina;
	}

	public void setNomina(java.lang.String nomina) {
		this.nomina = nomina;
	}

	public java.lang.String getAsistentContratada() {
		return this.asistentContratada;
	}

	public void setAsistentContratada(java.lang.String asistentContratada) {
		this.asistentContratada = asistentContratada;
	}

}